const INCREMENT_LOADING = 'INCREMENT_LOADING'
const DECREMENT_LOADING = 'DECREMENT_LOADING'
const FETCH_CHARACTERS = 'FETCH_CHARACTERS'
const INCREMENT_CHARACTERS_OFFSET = 'INCREMENT_CHARACTERS_OFFSET'
const SET_CHARACTERS_TOTAL = 'SET_CHARACTERS_TOTAL'
const FETCH_CHARACTERS_COMICS = 'FETCH_CHARACTERS_COMICS'

export {
  INCREMENT_LOADING,
  DECREMENT_LOADING,
  FETCH_CHARACTERS,
  INCREMENT_CHARACTERS_OFFSET,
  SET_CHARACTERS_TOTAL,
  FETCH_CHARACTERS_COMICS,
}
